services:
  backend:
    build:
      context: backend/
      target: development
      # dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/intheair
    # For better terminal interaction and graceful shutdown with Ctrl+C
    stdin_open: true
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=intheair
    volumes:
      - mysql_data:/var/lib/mysql
    # No need to expose MySQL to the outside world
    # ports:
      # - "3306:3306"
      # - "127.0.0.1:3306:3306"
    healthcheck:
      # test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 6

  phpmyadmin:
    image: phpmyadmin:5.2.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "7080:80"

volumes:
  mysql_data: