import { Injectable } from '@nestjs/common';

// import { TransmitterType } from '@prisma/client';
import { PrismaService } from './prisma/prisma.service';

@Injectable()
export class AppService {
  constructor(private readonly prisma: PrismaService) {}
  async getHello(): Promise<string> {
    // const create TransmitterType
    await this.prisma.transmitterType.create({
      data: {
        name: 'autogenerated-' + new Date().toISOString(),
      },
    });
    return 'Hello be!';
  }
}
